name: Todo CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: make install-dependencies

    - name: Lint
      run: make lint

    - name: Unit Test
      run: make test
    
    - name: E2E Test
      run: make e2e-test
